# ej 1


Construir arrays a partir de una lista simple
y una lista anidada usando tipos de datos
numéricos distintos para cada una.


In [2]:
import numpy as np

In [18]:
# listas con distintos tipos numéricos
lista_simple = [1, 2, 3]                    # enteros
lista_anidada = [[1.0, 2.0], [3.0, 4.0]]    # flotantes

array = np.array(lista_simple)
print(array)
print("-------------")
array = np.array(lista_anidada)
print(array)

[1 2 3]
-------------
[[1. 2.]
 [3. 4.]]


B. Construir un array lineal de 36 elementos.
Cambiar el shape para que tenga:
* 3 filas y 12 columnas
* 4 columnas

In [30]:
# crear un vector de 36 valores aleatorios
arr_rand = np.random.rand(36)  # números en [0, 1)

print(arr_rand.reshape(12,3))
print("------------------------")
print(arr_rand.reshape(9,4))




[[0.6749395  0.9835907  0.72706016]
 [0.06369234 0.79582127 0.82089175]
 [0.36649502 0.60065138 0.48980872]
 [0.8763963  0.9819608  0.07139163]
 [0.33406651 0.70931629 0.6768948 ]
 [0.57233158 0.68783462 0.28858696]
 [0.93249158 0.16901952 0.08260421]
 [0.97804579 0.16301168 0.0876388 ]
 [0.66863383 0.60367364 0.53344801]
 [0.24007606 0.57263761 0.35230588]
 [0.1906719  0.53642155 0.64080923]
 [0.68157939 0.93867145 0.47591739]]
------------------------
[[0.6749395  0.9835907  0.72706016 0.06369234]
 [0.79582127 0.82089175 0.36649502 0.60065138]
 [0.48980872 0.8763963  0.9819608  0.07139163]
 [0.33406651 0.70931629 0.6768948  0.57233158]
 [0.68783462 0.28858696 0.93249158 0.16901952]
 [0.08260421 0.97804579 0.16301168 0.0876388 ]
 [0.66863383 0.60367364 0.53344801 0.24007606]
 [0.57263761 0.35230588 0.1906719  0.53642155]
 [0.64080923 0.68157939 0.93867145 0.47591739]]


# Ejercicio 2
Dado un vector de pesos(kg) y otro vector
alturas(metros), calcular el índice de masa
corporal general (un vector imc).


In [40]:
pesos = np.array([50,65.5,89.2,100])
alturas = np.array([1.6,1.7,1.8,1.75])
alturas_imc = np.square(alturas)

print (pesos/alturas_imc)



[19.53125    22.66435986 27.5308642  32.65306122]


# Ejercicio 3
1. Crear un vector con diez números, todos ceros.
2. Crear un vector con diez números al azar.
3. Crear una matriz de 2x3 y multiplicarla por su
traspuesta. Lo pedido sería algo así: A*AT .
(Matriz transpuesta es, en álgebra, una matriz que se
forma al cambiar filas por columnas de la matriz original).

In [75]:
zeros = np.zeros(10)
random = np.random.random(10)
# print(zeros)
# print(random)

matriz = np.array([
    [1,2],
    [4,5]
])
matriz * np.transpose(matriz)

array([[ 1,  8],
       [ 8, 25]])