# NUMPY

__es una libreria principal de calculo numerico y el ecosistema de las librerias cietificas del lenguaje ( como pandas y matolib). se basa en arrays y serie de funciones muy optimizadas para su manipulacion__ 

## arrays

es una estructura que permite acelerar las operaciones matematicas, sin la necesidad de recurrir a bucles para operar con todos sus elementos, esto se le llama __vectorizacion__ 
tiene datos mas optimizados pero acambio no tiene mucha flexibilidad

## atributos de un array

* __dtype__: el tipo de dato
* __size__: cantidad de elemntos
* __nbytes__: total de bytes consumidos por datos
* _ndim__: numero de edimensiones
* __shape__: cantidad de elementos en cada dimension
* __strides__: cantidad de bytes para moverse en una posicion de cada dimension

## tipos de datos



* int = 8,16,32,64 bits (int8,etc)
* Uint = 8,16,32,64 bits (unit8,etc)
* bool = bool
* float = 16,32,64,128 bits( float16,etc)
* complex = 64,128,256 bits

## creacion de arrays

In [26]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5] , dtype = np.float64)
arr3 = np.array([1,2,3,4,5], dtype= np.int8)


print(arr1,arr1.dtype,arr1.nbytes)
print(arr2, arr3.dtype,arr2.nbytes)
print(arr3, arr3.dtype,arr3.nbytes)

[1 2 3 4 5] int64 40
[1. 2. 3. 4. 5.] int8 40
[1 2 3 4 5] int8 5


In [27]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,1,0,1]
])
print(arr)
print("ndim: ", arr.ndim, "---- shape: ",arr.shape)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 0 1]]
ndim:  2 ---- shape:  (3, 4)


Además hay numerosas funciones para crear arrays:
* arange y linspace para rangos de números equiespaciados.
* zeros, ones y full para arrays de cualquier dimensión y forma.
* identity, eye y diagonal para arrays de 2 dimensiones.
- El módulo random permite crear arrays con distintas
distribuciones de números al azar.
- Las funciones loadtxt y genfromtxt permiten leer archivos de
texto tipo csv.


## reshaping


esto lo que permite es reacomodar los datos como yo necesite, es decir que si tengo una matriz de 3 filas y 4 columnas, puedo moverlo como yo quiera
(se tiene que respetar el 3x4, etnonces yo puedo hacer una matrices que den igual resultado que 3x4, en este caso 12 ej: 6x2)

In [28]:

array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


print(array.shape)        # (3, 3) → 9 elementos

# ejemplos válidos
print(array.reshape(9))   # vector de 9 elementos
print(array.reshape(1, 9)) # 1 fila, 9 columnas
print(array.reshape(9, 1)) # 9 filas, 1 columna

# el intento de hacer esto falla:
# array.reshape(6, 2)     # ValueError: cannot reshape array of size 9 into shape (6,2)

(3, 3)
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


## indexing


In [29]:
array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])



print(array[:2]) # hasta que fila
print()
print
print(array[2:]) #desde que fila (sin incluirla)

[[1 2 3]
 [4 5 6]]

[[7 8 9]]


## enmascaramiento


In [30]:
numeros = np.array([10,20,30,40])
mascara = np.array([True,False,False,True])

print(numeros[mascara]) #me devuelve los true

print(numeros > 30) # esto me crea una mascara de que numeros cumplen esa condicion y cuales no

print(numeros[numeros>20])

[10 40]
[False False False  True]
[30 40]


## asignaciones

In [ ]:
array = np.array([
    [1,2,3],
    [4,5,6]
])

array[:,2] = 0 # de todas las filas , agarra solo la columna 2
array[:1,2]=20
print(array)
array = np.array([
    [1,2,3],
    [4,5,6]
])
print("------------------------")
array[array<5] = 11
print(array)



[[ 1  2 20]
 [ 4  5  0]]
------------------------
[[11 11 11]
 [11  5  6]]
