# operaciones


Así mismo existen numerosas funciones para realizar operaciones
matemáticas elemento a elemento.
* Funciones trigonométricas (sin, cos, tan, arcsin, tanh, etc.)
* Logarítmicas (log, log2, log10, etc)
* Exponenciales (exp, exp2, expm1, etc.)
* Potenciales (square, sqrt, cbrt, reciprocal, etc.)
* Redondeo de decimales (round, rint, trunc, floor, ceil, etc.)
* Y muchas otras.

## broadcasting

se conoce como broadcasting el poder realizar operaciones en matices de distintas dimenciones , por ejemplo sumar una matriz de 3x4 a una de 1x4

In [ ]:
import numpy as np
array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
array2 = np.array([10,11,12])

print(array + array2) # esto es el broadcasting, es automatico

[[11 13 15]
 [14 16 18]
 [17 19 21]]


## operaciones logicas

In [6]:
print(array>3)
print("-------------------")
print(array[(array<5) & (array%2 ==0)])

[[False False False]
 [ True  True  True]
 [ True  True  True]]
-------------------
[2 4]
